#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Migrate polyData oracle tables from MySQL to PostgreSQL.

This script is intentionally separate from migrate_mysql_to_postgres.py:

- migrate_mysql_to_postgres.py migrates market core tables only.
- migrate_oracle_mysql_to_postgres.py migrates oracle evidence tables only.

Default oracle scope:

- oracle.uma_adapter_mapping
- oracle.neg_risk_request_mapping
- oracle.oracle_events

Optional:

- ops.sync_state via --include-sync-state
- rebuild core.market_status_snapshot from oracle.oracle_events unless
  --skip-market-status-rebuild is passed
"""

from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Mapping, Optional, Sequence, Tuple

try:
    import pymysql
    from pymysql.cursors import DictCursor
except ImportError:  # pragma: no cover - handled at runtime.
    pymysql = None
    DictCursor = None

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - handled at runtime.
    psycopg = None
    dict_row = None


PROJECT_ROOT = Path(__file__).resolve().parent


def _load_dotenv_files() -> None:
    try:
        from dotenv import load_dotenv
    except ImportError:
        return
    for candidate in (
        PROJECT_ROOT / ".env",
        PROJECT_ROOT / ".env.local",
        PROJECT_ROOT / "scripts" / ".env",
    ):
        if candidate.exists():
            load_dotenv(candidate, override=False)


_load_dotenv_files()


def env_first(*names: str, default: str = "") -> str:
    for name in names:
        value = os.environ.get(name)
        if value is not None and value != "":
            return value
    return default


DEFAULT_MYSQL_HOST = env_first("POLYMARKET_MYSQL_HOST", default="127.0.0.1")
DEFAULT_MYSQL_PORT = int(env_first("POLYMARKET_MYSQL_PORT", default="43306"))
DEFAULT_MYSQL_USER = env_first("POLYMARKET_MYSQL_USER", default="poly_user")
DEFAULT_MYSQL_PASSWORD = env_first("POLYMARKET_MYSQL_PASSWORD")
DEFAULT_MYSQL_DATABASE = env_first("POLYMARKET_MYSQL_DATABASE", default="poly_data")
DEFAULT_MYSQL_CHARSET = env_first("POLYMARKET_MYSQL_CHARSET", default="utf8mb4")

DEFAULT_PG_HOST = env_first(
    "POLYDATA_POSTGRES_HOST",
    "POLYMARKET_POSTGRES_HOST",
    "POLYMARKET_PostgreSQL_HOST",
    default="127.0.0.1",
)
DEFAULT_PG_PORT = int(
    env_first(
        "POLYDATA_POSTGRES_PORT",
        "POLYMARKET_POSTGRES_PORT",
        "POLYMARKET_PostgreSQL_PORT",
        default="45432",
    )
)
DEFAULT_PG_USER = env_first(
    "POLYDATA_POSTGRES_USER",
    "POLYMARKET_POSTGRES_USER",
    "POLYMARKET_PostgreSQL_USER",
    default="poly_user",
)
DEFAULT_PG_PASSWORD = env_first(
    "POLYDATA_POSTGRES_PASSWORD",
    "POLYMARKET_POSTGRES_PASSWORD",
    "POLYMARKET_POSTGRESQL_PASSWORD",
    "POLYMARKET_PostgreSQL_PASSWORD",
)
DEFAULT_PG_DATABASE = env_first(
    "POLYDATA_POSTGRES_DATABASE",
    "POLYMARKET_POSTGRES_DATABASE",
    "POLYMARKET_PostgreSQL_DATABASE",
    default="poly_data_core",
)

DEFAULT_BAD_ROWS_DIR = Path(
    os.environ.get(
        "POLYDATA_ORACLE_MIGRATION_BAD_ROWS_DIR",
        "data/postgres/backups/oracle_migration_bad_rows",
    )
)


ORACLE_SCHEMA_SQL = """
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS oracle;
CREATE SCHEMA IF NOT EXISTS ops;

CREATE TABLE IF NOT EXISTS oracle.uma_adapter_mapping (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ancillary_data TEXT NOT NULL,
  ancillary_data_hash TEXT GENERATED ALWAYS AS (
    encode(digest(ancillary_data, 'sha256'), 'hex')
  ) STORED,
  question_id TEXT NOT NULL,
  source_adapter TEXT,
  UNIQUE (ancillary_data_hash)
);

CREATE INDEX IF NOT EXISTS idx_uma_adapter_mapping_question_id
  ON oracle.uma_adapter_mapping (question_id);

CREATE TABLE IF NOT EXISTS oracle.neg_risk_request_mapping (
  request_id TEXT PRIMARY KEY,
  question_id TEXT NOT NULL,
  market_id TEXT,
  source_operator TEXT
);

CREATE INDEX IF NOT EXISTS idx_neg_risk_request_mapping_question_id
  ON oracle.neg_risk_request_mapping (question_id);

CREATE INDEX IF NOT EXISTS idx_neg_risk_request_mapping_source_operator
  ON oracle.neg_risk_request_mapping (source_operator);

CREATE TABLE IF NOT EXISTS oracle.oracle_events (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tx_hash TEXT NOT NULL,
  log_index BIGINT NOT NULL,
  block_number BIGINT NOT NULL,
  event_time TIMESTAMPTZ,
  raw_event_time TEXT,
  event_status TEXT NOT NULL CHECK (
    event_status IN ('request', 'propose', 'dispute', 'settle')
  ),
  external_market_id TEXT,
  market_id BIGINT REFERENCES core.markets(id),
  market_title TEXT,
  source_adapter TEXT,
  source_oracle TEXT,
  adapter_question_id TEXT,
  matched_by TEXT,
  question_id TEXT,
  condition_id TEXT,
  string_raw TEXT,
  p1 TEXT,
  p2 TEXT,
  proposed_price TEXT,
  settled_price TEXT,
  settlement_recipient TEXT,
  payout TEXT,
  requester TEXT,
  proposer TEXT,
  disputer TEXT,
  request_transaction TEXT,
  proposal_transaction TEXT,
  settlement_transaction TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (tx_hash, log_index)
);

CREATE INDEX IF NOT EXISTS idx_oracle_events_block ON oracle.oracle_events (block_number);
CREATE INDEX IF NOT EXISTS idx_oracle_events_market_id ON oracle.oracle_events (market_id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_external_market_id ON oracle.oracle_events (external_market_id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_question_id ON oracle.oracle_events (question_id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_condition_id ON oracle.oracle_events (condition_id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_market_block_id ON oracle.oracle_events (market_id, block_number, id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_external_market_block_id ON oracle.oracle_events (external_market_id, block_number, id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_question_block_id ON oracle.oracle_events (question_id, block_number, id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_condition_block_id ON oracle.oracle_events (condition_id, block_number, id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_status ON oracle.oracle_events (event_status);
CREATE INDEX IF NOT EXISTS idx_oracle_events_status_market_id ON oracle.oracle_events (event_status, market_id);
CREATE INDEX IF NOT EXISTS idx_oracle_events_matched_by ON oracle.oracle_events (matched_by);
CREATE INDEX IF NOT EXISTS idx_oracle_events_event_time ON oracle.oracle_events (event_time);

CREATE TABLE IF NOT EXISTS ops.sync_state (
  key TEXT PRIMARY KEY,
  value TEXT,
  last_block BIGINT,
  updated_at TIMESTAMPTZ
);
"""


REBUILD_MARKET_STATUS_SQL = """
TRUNCATE TABLE core.market_status_snapshot;

INSERT INTO core.market_status_snapshot (
  market_id,
  has_settle,
  has_propose,
  updated_at
)
SELECT
  market_id,
  bool_or(event_status = 'settle') AS has_settle,
  bool_or(event_status = 'propose') AS has_propose,
  now() AS updated_at
FROM oracle.oracle_events
WHERE market_id IS NOT NULL
GROUP BY market_id;
"""


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _normalize_timestamp_text(text: str) -> str:
    candidate = text.strip()
    if candidate.endswith("Z"):
        candidate = f"{candidate[:-1]}+00:00"
    if candidate.endswith(" UTC"):
        candidate = f"{candidate[:-4]}+00:00"
    return candidate


def parse_timestamp(value: Any) -> Tuple[Optional[datetime], Optional[str]]:
    if value is None:
        return None, None
    if isinstance(value, datetime):
        dt = value
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc), None

    text = str(value).strip()
    if not text or text.lower() in {"null", "none", "nan"}:
        return None, None

    candidate = _normalize_timestamp_text(text)
    try:
        dt = datetime.fromisoformat(candidate)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc), None
    except ValueError:
        pass

    for fmt in (
        "%Y-%m-%d %H:%M:%S.%f",
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d",
    ):
        try:
            dt = datetime.strptime(text, fmt).replace(tzinfo=timezone.utc)
            return dt, None
        except ValueError:
            continue
    return None, text


def require_drivers() -> None:
    missing = []
    if pymysql is None:
        missing.append("PyMySQL")
    if psycopg is None:
        missing.append("psycopg[binary]")
    if missing:
        raise SystemExit(
            "Missing Python database driver(s): "
            + ", ".join(missing)
            + ". Install with: python -m pip install -r scripts/requirements.txt"
        )


def quote_ident(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def quote_table(name: str) -> str:
    return ".".join(quote_ident(part) for part in name.split("."))


class BadRowLogger:
    def __init__(self, root: Path) -> None:
        self.root = root
        self._handles: Dict[str, Any] = {}

    def log(self, table: str, row: Mapping[str, Any], reason: str) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        handle = self._handles.get(table)
        if handle is None:
            handle = (self.root / f"{table}.jsonl").open("a", encoding="utf-8")
            self._handles[table] = handle
        identity = {
            "id": row.get("id"),
            "tx_hash": row.get("tx_hash"),
            "log_index": row.get("log_index"),
            "request_id": row.get("request_id"),
            "key": row.get("key"),
        }
        payload = {"reason": reason, "identity": identity}
        handle.write(json.dumps(payload, ensure_ascii=False, default=str))
        handle.write("\n")
        handle.flush()

    def close(self) -> None:
        for handle in self._handles.values():
            handle.close()
        self._handles.clear()


TransformFn = Callable[[Mapping[str, Any], BadRowLogger], Dict[str, Any]]


@dataclass(frozen=True)
class TableSpec:
    key: str
    source_table: str
    target_table: str
    source_columns: Sequence[str]
    target_columns: Sequence[str]
    conflict_columns: Sequence[str]
    order_column: str
    transform: TransformFn


def sanitize_pg_text_fields(
    table: str,
    source_row: Mapping[str, Any],
    transformed_row: Mapping[str, Any],
    bad_rows: BadRowLogger,
) -> Dict[str, Any]:
    cleaned: Dict[str, Any] = {}
    for column, value in transformed_row.items():
        if isinstance(value, bytes):
            text = value.decode("utf-8", errors="replace")
            if "\x00" in text:
                bad_rows.log(
                    table,
                    source_row,
                    f"{column} contained {text.count(chr(0))} NUL bytes; removed before PostgreSQL insert",
                )
                text = text.replace("\x00", "")
            cleaned[column] = text
            continue

        if isinstance(value, str) and "\x00" in value:
            bad_rows.log(
                table,
                source_row,
                f"{column} contained {value.count(chr(0))} NUL bytes; removed before PostgreSQL insert",
            )
            value = value.replace("\x00", "")
        cleaned[column] = value
    return cleaned


def transform_uma_adapter_mapping(row: Mapping[str, Any], bad_rows: BadRowLogger) -> Dict[str, Any]:
    return {
        "id": row["id"],
        "ancillary_data": row.get("ancillary_data"),
        "question_id": row.get("question_id"),
        "source_adapter": row.get("source_adapter"),
    }


def transform_neg_risk_request_mapping(row: Mapping[str, Any], bad_rows: BadRowLogger) -> Dict[str, Any]:
    return {
        "request_id": row.get("request_id"),
        "question_id": row.get("question_id"),
        "market_id": row.get("market_id"),
        "source_operator": row.get("source_operator"),
    }


def transform_oracle_events(row: Mapping[str, Any], bad_rows: BadRowLogger) -> Dict[str, Any]:
    event_time, raw_event_time = parse_timestamp(row.get("event_time"))
    created_at, raw_created_at = parse_timestamp(row.get("created_at"))
    if raw_created_at is not None:
        bad_rows.log("oracle_events", row, "created_at could not be parsed; using current UTC time")
    return {
        "id": row["id"],
        "tx_hash": row.get("tx_hash"),
        "log_index": row.get("log_index"),
        "block_number": row.get("block_number"),
        "event_time": event_time,
        "raw_event_time": raw_event_time,
        "event_status": row.get("event_status"),
        "external_market_id": row.get("external_market_id"),
        "market_id": row.get("market_id"),
        "market_title": row.get("market_title"),
        "source_adapter": row.get("source_adapter"),
        "source_oracle": row.get("source_oracle"),
        "adapter_question_id": row.get("adapter_question_id"),
        "matched_by": row.get("matched_by"),
        "question_id": row.get("question_id"),
        "condition_id": row.get("condition_id"),
        "string_raw": row.get("string_raw"),
        "p1": row.get("p1"),
        "p2": row.get("p2"),
        "proposed_price": row.get("proposed_price"),
        "settled_price": row.get("settled_price"),
        "settlement_recipient": row.get("settlement_recipient"),
        "payout": row.get("payout"),
        "requester": row.get("requester"),
        "proposer": row.get("proposer"),
        "disputer": row.get("disputer"),
        "request_transaction": row.get("request_transaction"),
        "proposal_transaction": row.get("proposal_transaction"),
        "settlement_transaction": row.get("settlement_transaction"),
        "created_at": created_at or _utc_now(),
    }


def transform_sync_state(row: Mapping[str, Any], bad_rows: BadRowLogger) -> Dict[str, Any]:
    updated_at, raw_updated_at = parse_timestamp(row.get("updated_at"))
    if raw_updated_at is not None:
        bad_rows.log("sync_state", row, "updated_at could not be parsed")
    return {
        "key": row.get("key"),
        "value": row.get("value"),
        "last_block": row.get("last_block"),
        "updated_at": updated_at,
    }


TABLE_SPECS: Dict[str, TableSpec] = {
    "uma_adapter_mapping": TableSpec(
        key="uma_adapter_mapping",
        source_table="uma_adapter_mapping",
        target_table="oracle.uma_adapter_mapping",
        source_columns=("id", "ancillary_data", "question_id", "source_adapter"),
        target_columns=("id", "ancillary_data", "question_id", "source_adapter"),
        conflict_columns=("id",),
        order_column="id",
        transform=transform_uma_adapter_mapping,
    ),
    "neg_risk_request_mapping": TableSpec(
        key="neg_risk_request_mapping",
        source_table="neg_risk_request_mapping",
        target_table="oracle.neg_risk_request_mapping",
        source_columns=("request_id", "question_id", "market_id", "source_operator"),
        target_columns=("request_id", "question_id", "market_id", "source_operator"),
        conflict_columns=("request_id",),
        order_column="request_id",
        transform=transform_neg_risk_request_mapping,
    ),
    "oracle_events": TableSpec(
        key="oracle_events",
        source_table="oracle_events",
        target_table="oracle.oracle_events",
        source_columns=(
            "id",
            "tx_hash",
            "log_index",
            "block_number",
            "event_time",
            "event_status",
            "external_market_id",
            "market_id",
            "market_title",
            "source_adapter",
            "source_oracle",
            "adapter_question_id",
            "matched_by",
            "question_id",
            "condition_id",
            "string_raw",
            "p1",
            "p2",
            "proposed_price",
            "settled_price",
            "settlement_recipient",
            "payout",
            "requester",
            "proposer",
            "disputer",
            "request_transaction",
            "proposal_transaction",
            "settlement_transaction",
            "created_at",
        ),
        target_columns=(
            "id",
            "tx_hash",
            "log_index",
            "block_number",
            "event_time",
            "raw_event_time",
            "event_status",
            "external_market_id",
            "market_id",
            "market_title",
            "source_adapter",
            "source_oracle",
            "adapter_question_id",
            "matched_by",
            "question_id",
            "condition_id",
            "string_raw",
            "p1",
            "p2",
            "proposed_price",
            "settled_price",
            "settlement_recipient",
            "payout",
            "requester",
            "proposer",
            "disputer",
            "request_transaction",
            "proposal_transaction",
            "settlement_transaction",
            "created_at",
        ),
        conflict_columns=("id",),
        order_column="id",
        transform=transform_oracle_events,
    ),
    "sync_state": TableSpec(
        key="sync_state",
        source_table="sync_state",
        target_table="ops.sync_state",
        source_columns=("key", "value", "last_block", "updated_at"),
        target_columns=("key", "value", "last_block", "updated_at"),
        conflict_columns=("key",),
        order_column="key",
        transform=transform_sync_state,
    ),
}

DEFAULT_TABLES = ("uma_adapter_mapping", "neg_risk_request_mapping", "oracle_events")
TRUNCATE_TARGETS = (
    "oracle.oracle_events",
    "oracle.uma_adapter_mapping",
    "oracle.neg_risk_request_mapping",
    "ops.sync_state",
)


def expand_tables(raw: str, include_sync_state: bool) -> List[str]:
    if raw.strip().lower() == "oracle":
        tables = list(DEFAULT_TABLES)
    else:
        tables = []
        for part in raw.split(","):
            item = part.strip()
            if not item:
                continue
            if item not in TABLE_SPECS:
                valid = sorted(["oracle", *TABLE_SPECS.keys()])
                raise SystemExit(f"Unknown table/group {item!r}. Valid values: {', '.join(valid)}")
            if item not in tables:
                tables.append(item)
    if include_sync_state and "sync_state" not in tables:
        tables.append("sync_state")
    return tables


def mysql_connect(args: argparse.Namespace):
    require_drivers()
    return pymysql.connect(
        host=args.mysql_host,
        port=args.mysql_port,
        user=args.mysql_user,
        password=args.mysql_password,
        database=args.mysql_database,
        charset=args.mysql_charset,
        cursorclass=DictCursor,
        autocommit=False,
        read_timeout=args.mysql_read_timeout,
        write_timeout=args.mysql_write_timeout,
    )


def pg_connect(args: argparse.Namespace):
    require_drivers()
    return psycopg.connect(
        host=args.postgres_host,
        port=args.postgres_port,
        user=args.postgres_user,
        password=args.postgres_password,
        dbname=args.postgres_database,
        row_factory=dict_row,
        autocommit=False,
    )


def create_schema(pg_conn) -> None:
    with pg_conn.cursor() as cur:
        cur.execute(ORACLE_SCHEMA_SQL)
    pg_conn.commit()


def assert_core_markets_ready(pg_conn) -> None:
    with pg_conn.cursor() as cur:
        cur.execute("SELECT to_regclass('core.markets') AS rel")
        row = cur.fetchone()
        if not row or row["rel"] is None:
            raise RuntimeError("core.markets does not exist; migrate market data before oracle data")
        cur.execute("SELECT COUNT(*) AS c FROM core.markets")
        count = int(cur.fetchone()["c"])
        if count <= 0:
            raise RuntimeError("core.markets is empty; migrate market data before oracle data")


def make_upsert_sql(spec: TableSpec) -> str:
    target = quote_table(spec.target_table)
    columns = ", ".join(quote_ident(col) for col in spec.target_columns)
    placeholders = ", ".join(f"%({col})s" for col in spec.target_columns)
    conflicts = ", ".join(quote_ident(col) for col in spec.conflict_columns)
    update_columns = [col for col in spec.target_columns if col not in spec.conflict_columns]
    if update_columns:
        updates = ", ".join(
            f"{quote_ident(col)} = EXCLUDED.{quote_ident(col)}" for col in update_columns
        )
        conflict_clause = f"DO UPDATE SET {updates}"
    else:
        conflict_clause = "DO NOTHING"
    return (
        f"INSERT INTO {target} ({columns}) VALUES ({placeholders}) "
        f"ON CONFLICT ({conflicts}) {conflict_clause}"
    )


def mysql_count(mysql_conn, table: str, limit: Optional[int] = None) -> int:
    with mysql_conn.cursor() as cur:
        if limit is None:
            cur.execute(f"SELECT COUNT(*) AS c FROM `{table}`")
        else:
            cur.execute(f"SELECT COUNT(*) AS c FROM (SELECT 1 FROM `{table}` LIMIT %s) AS t", (limit,))
        row = cur.fetchone()
        return int(row["c"] if row else 0)


def pg_count(pg_conn, target_table: str) -> int:
    with pg_conn.cursor() as cur:
        cur.execute(f"SELECT COUNT(*) AS c FROM {quote_table(target_table)}")
        row = cur.fetchone()
        return int(row["c"] if row else 0)


def safe_pg_count(pg_conn, target_table: str) -> Optional[int]:
    try:
        return pg_count(pg_conn, target_table)
    except Exception:
        pg_conn.rollback()
        return None


def pg_max_value(pg_conn, target_table: str, column: str) -> Any:
    with pg_conn.cursor() as cur:
        cur.execute(f"SELECT MAX({quote_ident(column)}) AS v FROM {quote_table(target_table)}")
        row = cur.fetchone()
        return row["v"] if row else None


def fetch_mysql_batch(
    mysql_conn,
    spec: TableSpec,
    last_value: Any,
    batch_size: int,
    remaining: Optional[int],
) -> List[Mapping[str, Any]]:
    columns = ", ".join(f"`{col}`" for col in spec.source_columns)
    limit = batch_size if remaining is None else min(batch_size, remaining)
    where_sql = ""
    params: List[Any] = []
    if last_value is not None:
        where_sql = f"WHERE `{spec.order_column}` > %s"
        params.append(last_value)
    params.append(limit)
    sql = (
        f"SELECT {columns} FROM `{spec.source_table}` "
        f"{where_sql} ORDER BY `{spec.order_column}` LIMIT %s"
    )
    with mysql_conn.cursor() as cur:
        cur.execute(sql, tuple(params))
        return list(cur.fetchall())


def write_rows(
    pg_conn,
    spec: TableSpec,
    rows: Sequence[Mapping[str, Any]],
    *,
    skip_bad_rows: bool,
    bad_rows: BadRowLogger,
) -> int:
    if not rows:
        return 0
    sql = make_upsert_sql(spec)
    try:
        with pg_conn.cursor() as cur:
            cur.executemany(sql, rows)
        pg_conn.commit()
        return len(rows)
    except Exception:
        pg_conn.rollback()
        if not skip_bad_rows:
            raise

    inserted = 0
    with pg_conn.cursor() as cur:
        for row in rows:
            try:
                cur.execute(sql, row)
                inserted += 1
            except Exception as exc:  # pragma: no cover - row-specific recovery path.
                pg_conn.rollback()
                bad_rows.log(spec.key, row, f"postgres insert failed: {exc}")
            else:
                pg_conn.commit()
    return inserted


def migrate_one_table(
    mysql_conn,
    pg_conn,
    spec: TableSpec,
    args: argparse.Namespace,
    bad_rows: BadRowLogger,
) -> int:
    source_count = mysql_count(mysql_conn, spec.source_table, args.limit_per_table)
    if args.dry_run:
        target_count = safe_pg_count(pg_conn, spec.target_table)
        target_text = "missing" if target_count is None else str(target_count)
        print(
            f"[dry-run] {spec.key}: source_count={source_count} "
            f"target_count={target_text} target={spec.target_table}",
            flush=True,
        )
        return 0

    remaining = args.limit_per_table
    last_value = None
    if args.resume and args.limit_per_table is None:
        last_value = pg_max_value(pg_conn, spec.target_table, spec.order_column)
        if last_value is not None:
            print(f"  [{spec.key}] resume from {spec.order_column}>{last_value}", flush=True)

    migrated = 0
    while remaining is None or remaining > 0:
        batch = fetch_mysql_batch(mysql_conn, spec, last_value, args.batch_size, remaining)
        if not batch:
            break
        transformed: List[Dict[str, Any]] = []
        for row in batch:
            try:
                transformed_row = spec.transform(row, bad_rows)
                transformed.append(
                    sanitize_pg_text_fields(spec.key, row, transformed_row, bad_rows)
                )
            except Exception as exc:
                bad_rows.log(spec.key, row, f"transform failed: {exc}")
                if not args.skip_bad_rows:
                    raise
        if transformed:
            migrated += write_rows(
                pg_conn,
                spec,
                transformed,
                skip_bad_rows=args.skip_bad_rows,
                bad_rows=bad_rows,
            )
        last_value = batch[-1][spec.order_column]
        if remaining is not None:
            remaining -= len(batch)
        print(
            f"  [{spec.key}] migrated={migrated} source_count={source_count} "
            f"last_{spec.order_column}={last_value}",
            flush=True,
        )
    return migrated


def truncate_targets(pg_conn, selected_tables: Sequence[str], rebuild_market_status: bool) -> None:
    selected_targets = [TABLE_SPECS[name].target_table for name in selected_tables]
    if rebuild_market_status:
        selected_targets.append("core.market_status_snapshot")
    ordered = [target for target in TRUNCATE_TARGETS if target in set(selected_targets)]
    if not ordered and not rebuild_market_status:
        return
    if ordered:
        sql = "TRUNCATE TABLE " + ", ".join(quote_table(t) for t in ordered) + " RESTART IDENTITY CASCADE"
        with pg_conn.cursor() as cur:
            cur.execute(sql)
        pg_conn.commit()
        print(f"[truncate] {', '.join(ordered)}", flush=True)
    if rebuild_market_status:
        with pg_conn.cursor() as cur:
            cur.execute("TRUNCATE TABLE core.market_status_snapshot")
        pg_conn.commit()
        print("[truncate] core.market_status_snapshot", flush=True)


def rebuild_market_status(pg_conn, dry_run: bool) -> None:
    if dry_run:
        print("[dry-run] would rebuild core.market_status_snapshot from oracle.oracle_events", flush=True)
        return
    with pg_conn.cursor() as cur:
        cur.execute(REBUILD_MARKET_STATUS_SQL)
    pg_conn.commit()
    print("[rebuild] core.market_status_snapshot rebuilt from oracle.oracle_events", flush=True)


def verify_counts(
    mysql_conn,
    pg_conn,
    selected_tables: Sequence[str],
    limit: Optional[int],
    *,
    dry_run: bool,
) -> None:
    print("[verify] row counts", flush=True)
    for name in selected_tables:
        spec = TABLE_SPECS[name]
        source_count = mysql_count(mysql_conn, spec.source_table, limit)
        target_count = safe_pg_count(pg_conn, spec.target_table)
        if target_count is None:
            print(f"  [missing] {name}: source={source_count} target=missing", flush=True)
            if not dry_run:
                raise RuntimeError(f"target table missing for {name}: {spec.target_table}")
            continue
        status = "ok" if limit is not None or source_count == target_count else "mismatch"
        print(f"  [{status}] {name}: source={source_count} target={target_count}", flush=True)
        if limit is None and source_count != target_count:
            raise RuntimeError(f"row count mismatch for {name}: source={source_count} target={target_count}")


def verify_market_bindings(pg_conn) -> None:
    with pg_conn.cursor() as cur:
        cur.execute(
            """
            SELECT COUNT(*) AS orphan_count
            FROM oracle.oracle_events oe
            LEFT JOIN core.markets m ON m.id = oe.market_id
            WHERE oe.market_id IS NOT NULL AND m.id IS NULL
            """
        )
        orphan_count = int(cur.fetchone()["orphan_count"])
        cur.execute(
            """
            SELECT
              COUNT(*) AS event_count,
              COUNT(*) FILTER (WHERE market_id IS NOT NULL) AS bound_event_count,
              COUNT(DISTINCT market_id) FILTER (WHERE market_id IS NOT NULL) AS bound_market_count,
              COUNT(DISTINCT market_id) FILTER (
                WHERE market_id IS NOT NULL AND event_status = 'settle'
              ) AS settled_market_count
            FROM oracle.oracle_events
            """
        )
        row = cur.fetchone()
    print("[verify] oracle market binding", flush=True)
    print(
        "  "
        f"events={row['event_count']} bound_events={row['bound_event_count']} "
        f"bound_markets={row['bound_market_count']} settled_markets={row['settled_market_count']} "
        f"orphans={orphan_count}",
        flush=True,
    )
    if orphan_count:
        raise RuntimeError(f"oracle_events has {orphan_count} orphan market_id values")


def print_status_distribution(pg_conn) -> None:
    with pg_conn.cursor() as cur:
        cur.execute(
            """
            SELECT has_settle, has_propose, COUNT(*) AS c
            FROM core.market_status_snapshot
            GROUP BY has_settle, has_propose
            ORDER BY has_settle, has_propose
            """
        )
        rows = cur.fetchall()
    print("[verify] rebuilt market_status_snapshot distribution", flush=True)
    print(f"  postgres: {rows}", flush=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Migrate polyData oracle data from MySQL to PostgreSQL")
    parser.add_argument("--mysql-host", default=DEFAULT_MYSQL_HOST)
    parser.add_argument("--mysql-port", type=int, default=DEFAULT_MYSQL_PORT)
    parser.add_argument("--mysql-user", default=DEFAULT_MYSQL_USER)
    parser.add_argument("--mysql-database", default=DEFAULT_MYSQL_DATABASE)
    parser.add_argument("--mysql-charset", default=DEFAULT_MYSQL_CHARSET)
    parser.add_argument("--mysql-read-timeout", type=int, default=3600)
    parser.add_argument("--mysql-write-timeout", type=int, default=3600)

    parser.add_argument("--postgres-host", default=DEFAULT_PG_HOST)
    parser.add_argument("--postgres-port", type=int, default=DEFAULT_PG_PORT)
    parser.add_argument("--postgres-user", default=DEFAULT_PG_USER)
    parser.add_argument("--postgres-database", default=DEFAULT_PG_DATABASE)

    parser.add_argument(
        "--tables",
        default="oracle",
        help="Comma separated oracle tables, or group 'oracle'. Default: oracle",
    )
    parser.add_argument("--include-sync-state", action="store_true", help="Also migrate ops.sync_state")
    parser.add_argument("--batch-size", type=int, default=10000)
    parser.add_argument("--limit-per-table", type=int, default=None)
    parser.add_argument("--bad-rows-dir", default=str(DEFAULT_BAD_ROWS_DIR))
    parser.add_argument("--create-schema", action="store_true", help="Create oracle/ops target schemas and tables first")
    parser.add_argument("--schema-only", action="store_true", help="Create schema and exit")
    parser.add_argument("--truncate-target", action="store_true", help="Truncate selected target oracle tables first")
    parser.add_argument("--resume", action="store_true", help="Resume from target max(order_column)")
    parser.add_argument("--skip-bad-rows", action="store_true", help="Log and skip transform/insert failures")
    parser.add_argument("--verify", action="store_true", help="Verify row counts and market bindings after migration")
    parser.add_argument(
        "--skip-market-status-rebuild",
        action="store_true",
        help="Do not rebuild core.market_status_snapshot after importing oracle_events",
    )
    parser.add_argument("--dry-run", action="store_true", help="Connect and print counts without writing")
    parser.add_argument("--yes", action="store_true", help="Confirm that writes to PostgreSQL are intended")
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()
    args.mysql_password = DEFAULT_MYSQL_PASSWORD
    args.postgres_password = DEFAULT_PG_PASSWORD
    selected_tables = expand_tables(args.tables, include_sync_state=args.include_sync_state)
    rebuild_status = not args.skip_market_status_rebuild and "oracle_events" in selected_tables

    if args.batch_size <= 0:
        raise SystemExit("--batch-size must be positive")
    if args.limit_per_table is not None and args.limit_per_table <= 0:
        raise SystemExit("--limit-per-table must be positive when provided")
    if args.truncate_target and args.resume:
        raise SystemExit("--truncate-target and --resume cannot be used together")
    if args.schema_only:
        args.create_schema = True
    if not args.dry_run and not args.yes and not args.schema_only:
        raise SystemExit("Refusing to write PostgreSQL without --yes. Use --dry-run for a safe check.")

    require_drivers()

    print(
        "[connect] "
        f"mysql={args.mysql_user}@{args.mysql_host}:{args.mysql_port}/{args.mysql_database} "
        f"postgres={args.postgres_user}@{args.postgres_host}:{args.postgres_port}/{args.postgres_database}",
        flush=True,
    )
    print(
        f"[plan] tables={','.join(selected_tables)} "
        f"rebuild_market_status={rebuild_status} batch_size={args.batch_size} dry_run={args.dry_run}",
        flush=True,
    )

    bad_rows = BadRowLogger(Path(args.bad_rows_dir))
    try:
        mysql_conn = mysql_connect(args)
    except Exception as exc:
        raise SystemExit(
            "MySQL connection failed: "
            f"{args.mysql_user}@{args.mysql_host}:{args.mysql_port}/{args.mysql_database}: {exc}"
        ) from exc

    try:
        pg_conn = pg_connect(args)
    except Exception as exc:
        mysql_conn.close()
        raise SystemExit(
            "PostgreSQL connection failed: "
            f"{args.postgres_user}@{args.postgres_host}:{args.postgres_port}/{args.postgres_database}: {exc}"
        ) from exc

    try:
        assert_core_markets_ready(pg_conn)

        if args.create_schema:
            if args.dry_run:
                print("[dry-run] would create PostgreSQL oracle/ops schemas and tables", flush=True)
            else:
                create_schema(pg_conn)
                print("[schema] PostgreSQL oracle/ops schemas/tables are ready", flush=True)
        if args.schema_only:
            return

        if args.truncate_target:
            truncate_targets(pg_conn, selected_tables, rebuild_status)

        total = 0
        for name in selected_tables:
            spec = TABLE_SPECS[name]
            print(f"[migrate] {name}: {spec.source_table} -> {spec.target_table}", flush=True)
            total += migrate_one_table(mysql_conn, pg_conn, spec, args, bad_rows)

        if rebuild_status:
            rebuild_market_status(pg_conn, args.dry_run)

        if args.verify:
            verify_counts(
                mysql_conn,
                pg_conn,
                selected_tables,
                args.limit_per_table,
                dry_run=args.dry_run,
            )
            if "oracle_events" in selected_tables:
                if args.dry_run and safe_pg_count(pg_conn, "oracle.oracle_events") is None:
                    print("[verify] oracle market binding skipped; target table is missing", flush=True)
                else:
                    verify_market_bindings(pg_conn)
            if rebuild_status and not args.dry_run:
                print_status_distribution(pg_conn)

        print(f"[done] migrated_rows={total}", flush=True)
    finally:
        bad_rows.close()
        try:
            pg_conn.close()
        finally:
            mysql_conn.close()


if __name__ == "__main__":
    main()
