from __future__ import annotations

from typing import Any, Dict, List


WEATHER_CITIES: List[Dict[str, Any]] = [
    {"city_id": "new-york", "city": "New York", "country": "US", "region": "North America", "lat": 40.7128, "lon": -74.0060, "timezone": "America/New_York", "unit": "F", "icao": "KNYC", "polymarket_aliases": ["New York City", "NYC", "New York"], "news_query": "New York weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "chicago", "city": "Chicago", "country": "US", "region": "North America", "lat": 41.8781, "lon": -87.6298, "timezone": "America/Chicago", "unit": "F", "icao": "KORD", "polymarket_aliases": ["Chicago"], "news_query": "Chicago weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "dallas", "city": "Dallas", "country": "US", "region": "North America", "lat": 32.7767, "lon": -96.7970, "timezone": "America/Chicago", "unit": "F", "icao": "KDAL", "polymarket_aliases": ["Dallas"], "news_query": "Dallas weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "miami", "city": "Miami", "country": "US", "region": "North America", "lat": 25.7617, "lon": -80.1918, "timezone": "America/New_York", "unit": "F", "icao": "KMIA", "polymarket_aliases": ["Miami"], "news_query": "Miami weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "austin", "city": "Austin", "country": "US", "region": "North America", "lat": 30.2672, "lon": -97.7431, "timezone": "America/Chicago", "unit": "F", "icao": "KAUS", "polymarket_aliases": ["Austin"], "news_query": "Austin weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "atlanta", "city": "Atlanta", "country": "US", "region": "North America", "lat": 33.7490, "lon": -84.3880, "timezone": "America/New_York", "unit": "F", "icao": "KATL", "polymarket_aliases": ["Atlanta"], "news_query": "Atlanta weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "houston", "city": "Houston", "country": "US", "region": "North America", "lat": 29.7604, "lon": -95.3698, "timezone": "America/Chicago", "unit": "F", "icao": "KHOU", "polymarket_aliases": ["Houston"], "news_query": "Houston weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "denver", "city": "Denver", "country": "US", "region": "North America", "lat": 39.7392, "lon": -104.9903, "timezone": "America/Denver", "unit": "F", "icao": "KDEN", "polymarket_aliases": ["Denver"], "news_query": "Denver weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "mexico-city", "city": "Mexico City", "country": "MX", "region": "North America", "lat": 19.4326, "lon": -99.1332, "timezone": "America/Mexico_City", "unit": "C", "icao": "MMMX", "polymarket_aliases": ["Mexico City"], "news_query": "Mexico City weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "los-angeles", "city": "Los Angeles", "country": "US", "region": "North America", "lat": 34.0522, "lon": -118.2437, "timezone": "America/Los_Angeles", "unit": "F", "icao": "KLAX", "polymarket_aliases": ["Los Angeles", "LA"], "news_query": "Los Angeles weather OR forecast OR wind", "label_dx": 8, "label_dy": -12},
    {"city_id": "seattle", "city": "Seattle", "country": "US", "region": "North America", "lat": 47.6062, "lon": -122.3321, "timezone": "America/Los_Angeles", "unit": "F", "icao": "KSEA", "polymarket_aliases": ["Seattle"], "news_query": "Seattle weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "toronto", "city": "Toronto", "country": "CA", "region": "North America", "lat": 43.6532, "lon": -79.3832, "timezone": "America/Toronto", "unit": "C", "icao": "CYYZ", "polymarket_aliases": ["Toronto"], "news_query": "Toronto weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "london", "city": "London", "country": "GB", "region": "Europe", "lat": 51.5072, "lon": -0.1276, "timezone": "Europe/London", "unit": "C", "icao": "EGLL", "polymarket_aliases": ["London"], "news_query": "London weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "paris", "city": "Paris", "country": "FR", "region": "Europe", "lat": 48.8566, "lon": 2.3522, "timezone": "Europe/Paris", "unit": "C", "icao": "LFPG", "polymarket_aliases": ["Paris"], "news_query": "Paris weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "madrid", "city": "Madrid", "country": "ES", "region": "Europe", "lat": 40.4168, "lon": -3.7038, "timezone": "Europe/Madrid", "unit": "C", "icao": "LEMD", "polymarket_aliases": ["Madrid"], "news_query": "Madrid weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "milan", "city": "Milan", "country": "IT", "region": "Europe", "lat": 45.4642, "lon": 9.1900, "timezone": "Europe/Rome", "unit": "C", "icao": "LIML", "polymarket_aliases": ["Milan"], "news_query": "Milan weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "munich", "city": "Munich", "country": "DE", "region": "Europe", "lat": 48.1351, "lon": 11.5820, "timezone": "Europe/Berlin", "unit": "C", "icao": "EDDM", "polymarket_aliases": ["Munich"], "news_query": "Munich weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "warsaw", "city": "Warsaw", "country": "PL", "region": "Europe", "lat": 52.2297, "lon": 21.0122, "timezone": "Europe/Warsaw", "unit": "C", "icao": "EPWA", "polymarket_aliases": ["Warsaw"], "news_query": "Warsaw weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "amsterdam", "city": "Amsterdam", "country": "NL", "region": "Europe", "lat": 52.3676, "lon": 4.9041, "timezone": "Europe/Amsterdam", "unit": "C", "icao": "EHAM", "polymarket_aliases": ["Amsterdam"], "news_query": "Amsterdam weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "tel-aviv", "city": "Tel Aviv", "country": "IL", "region": "Middle East", "lat": 32.0853, "lon": 34.7818, "timezone": "Asia/Jerusalem", "unit": "C", "icao": "LLBG", "polymarket_aliases": ["Tel Aviv"], "news_query": "Tel Aviv weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "ankara", "city": "Ankara", "country": "TR", "region": "Middle East", "lat": 39.9334, "lon": 32.8597, "timezone": "Europe/Istanbul", "unit": "C", "icao": "LTAC", "polymarket_aliases": ["Ankara"], "news_query": "Ankara weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "beijing", "city": "Beijing", "country": "CN", "region": "Asia", "lat": 39.9042, "lon": 116.4074, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZBAA", "polymarket_aliases": ["Beijing"], "news_query": "Beijing weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "shanghai", "city": "Shanghai", "country": "CN", "region": "Asia", "lat": 31.2304, "lon": 121.4737, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZSSS", "polymarket_aliases": ["Shanghai"], "news_query": "Shanghai weather OR forecast OR typhoon", "label_dx": 8, "label_dy": -12},
    {"city_id": "shenzhen", "city": "Shenzhen", "country": "CN", "region": "Asia", "lat": 22.5431, "lon": 114.0579, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZGSZ", "polymarket_aliases": ["Shenzhen"], "news_query": "Shenzhen weather OR forecast OR typhoon", "label_dx": 8, "label_dy": -12},
    {"city_id": "singapore", "city": "Singapore", "country": "SG", "region": "Asia", "lat": 1.3521, "lon": 103.8198, "timezone": "Asia/Singapore", "unit": "C", "icao": "WSSS", "polymarket_aliases": ["Singapore"], "news_query": "Singapore weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "tokyo", "city": "Tokyo", "country": "JP", "region": "Asia", "lat": 35.6762, "lon": 139.6503, "timezone": "Asia/Tokyo", "unit": "C", "icao": "RJTT", "polymarket_aliases": ["Tokyo"], "news_query": "Tokyo weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "seoul", "city": "Seoul", "country": "KR", "region": "Asia", "lat": 37.5665, "lon": 126.9780, "timezone": "Asia/Seoul", "unit": "C", "icao": "RKSI", "polymarket_aliases": ["Seoul"], "news_query": "Seoul weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "chengdu", "city": "Chengdu", "country": "CN", "region": "Asia", "lat": 30.5728, "lon": 104.0668, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZUUU", "polymarket_aliases": ["Chengdu"], "news_query": "Chengdu weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "chongqing", "city": "Chongqing", "country": "CN", "region": "Asia", "lat": 29.5630, "lon": 106.5516, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZUCK", "polymarket_aliases": ["Chongqing"], "news_query": "Chongqing weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "wuhan", "city": "Wuhan", "country": "CN", "region": "Asia", "lat": 30.5928, "lon": 114.3055, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZHHH", "polymarket_aliases": ["Wuhan"], "news_query": "Wuhan weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "buenos-aires", "city": "Buenos Aires", "country": "AR", "region": "South America", "lat": -34.6037, "lon": -58.3816, "timezone": "America/Argentina/Buenos_Aires", "unit": "C", "icao": "SABE", "polymarket_aliases": ["Buenos Aires"], "news_query": "Buenos Aires weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "sao-paulo", "city": "Sao Paulo", "country": "BR", "region": "South America", "lat": -23.5558, "lon": -46.6396, "timezone": "America/Sao_Paulo", "unit": "C", "icao": "SBSP", "polymarket_aliases": ["Sao Paulo", "São Paulo"], "news_query": "Sao Paulo weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "wellington", "city": "Wellington", "country": "NZ", "region": "Oceania", "lat": -41.2865, "lon": 174.7762, "timezone": "Pacific/Auckland", "unit": "C", "icao": "NZWN", "polymarket_aliases": ["Wellington"], "news_query": "Wellington weather OR forecast OR wind", "label_dx": 8, "label_dy": -12},
]


def load_weather_cities(limit: int | None = None) -> List[Dict[str, Any]]:
    rows = [dict(city) for city in WEATHER_CITIES]
    if limit is None:
        return rows
    return rows[: max(1, min(int(limit), len(rows)))]
