from __future__ import annotations

from typing import Any, Dict, List


WEATHER_CITIES: List[Dict[str, Any]] = [
    {"city_id": "new-york", "city": "New York", "country": "US", "region": "North America", "lat": 40.7128, "lon": -74.0060, "timezone": "America/New_York", "unit": "F", "icao": "KNYC", "polymarket_aliases": ["New York City", "NYC", "New York"], "news_query": "New York weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "chicago", "city": "Chicago", "country": "US", "region": "North America", "lat": 41.8781, "lon": -87.6298, "timezone": "America/Chicago", "unit": "F", "icao": "KORD", "polymarket_aliases": ["Chicago"], "news_query": "Chicago weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "dallas", "city": "Dallas", "country": "US", "region": "North America", "lat": 32.7767, "lon": -96.7970, "timezone": "America/Chicago", "unit": "F", "icao": "KDAL", "polymarket_aliases": ["Dallas"], "news_query": "Dallas weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "miami", "city": "Miami", "country": "US", "region": "North America", "lat": 25.7617, "lon": -80.1918, "timezone": "America/New_York", "unit": "F", "icao": "KMIA", "polymarket_aliases": ["Miami"], "news_query": "Miami weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "austin", "city": "Austin", "country": "US", "region": "North America", "lat": 30.2672, "lon": -97.7431, "timezone": "America/Chicago", "unit": "F", "icao": "KAUS", "polymarket_aliases": ["Austin"], "news_query": "Austin weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "atlanta", "city": "Atlanta", "country": "US", "region": "North America", "lat": 33.7490, "lon": -84.3880, "timezone": "America/New_York", "unit": "F", "icao": "KATL", "polymarket_aliases": ["Atlanta"], "news_query": "Atlanta weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "houston", "city": "Houston", "country": "US", "region": "North America", "lat": 29.7604, "lon": -95.3698, "timezone": "America/Chicago", "unit": "F", "icao": "KHOU", "polymarket_aliases": ["Houston"], "news_query": "Houston weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "denver", "city": "Denver", "country": "US", "region": "North America", "lat": 39.7392, "lon": -104.9903, "timezone": "America/Denver", "unit": "F", "icao": "KDEN", "polymarket_aliases": ["Denver"], "news_query": "Denver weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "mexico-city", "city": "Mexico City", "country": "MX", "region": "North America", "lat": 19.4326, "lon": -99.1332, "timezone": "America/Mexico_City", "unit": "C", "icao": "MMMX", "polymarket_aliases": ["Mexico City"], "news_query": "Mexico City weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "los-angeles", "city": "Los Angeles", "country": "US", "region": "North America", "lat": 34.0522, "lon": -118.2437, "timezone": "America/Los_Angeles", "unit": "F", "icao": "KLAX", "polymarket_aliases": ["Los Angeles", "LA"], "news_query": "Los Angeles weather OR forecast OR wind", "label_dx": 8, "label_dy": -12},
    {"city_id": "seattle", "city": "Seattle", "country": "US", "region": "North America", "lat": 47.6062, "lon": -122.3321, "timezone": "America/Los_Angeles", "unit": "F", "icao": "KSEA", "polymarket_aliases": ["Seattle"], "news_query": "Seattle weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "toronto", "city": "Toronto", "country": "CA", "region": "North America", "lat": 43.6532, "lon": -79.3832, "timezone": "America/Toronto", "unit": "C", "icao": "CYYZ", "polymarket_aliases": ["Toronto"], "news_query": "Toronto weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "london", "city": "London", "country": "GB", "region": "Europe", "lat": 51.5072, "lon": -0.1276, "timezone": "Europe/London", "unit": "C", "icao": "EGLL", "polymarket_aliases": ["London"], "news_query": "London weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "paris", "city": "Paris", "country": "FR", "region": "Europe", "lat": 48.8566, "lon": 2.3522, "timezone": "Europe/Paris", "unit": "C", "icao": "LFPG", "polymarket_aliases": ["Paris"], "news_query": "Paris weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "madrid", "city": "Madrid", "country": "ES", "region": "Europe", "lat": 40.4168, "lon": -3.7038, "timezone": "Europe/Madrid", "unit": "C", "icao": "LEMD", "polymarket_aliases": ["Madrid"], "news_query": "Madrid weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "milan", "city": "Milan", "country": "IT", "region": "Europe", "lat": 45.4642, "lon": 9.1900, "timezone": "Europe/Rome", "unit": "C", "icao": "LIML", "polymarket_aliases": ["Milan"], "news_query": "Milan weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "munich", "city": "Munich", "country": "DE", "region": "Europe", "lat": 48.1351, "lon": 11.5820, "timezone": "Europe/Berlin", "unit": "C", "icao": "EDDM", "polymarket_aliases": ["Munich"], "news_query": "Munich weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "warsaw", "city": "Warsaw", "country": "PL", "region": "Europe", "lat": 52.2297, "lon": 21.0122, "timezone": "Europe/Warsaw", "unit": "C", "icao": "EPWA", "polymarket_aliases": ["Warsaw"], "news_query": "Warsaw weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "amsterdam", "city": "Amsterdam", "country": "NL", "region": "Europe", "lat": 52.3676, "lon": 4.9041, "timezone": "Europe/Amsterdam", "unit": "C", "icao": "EHAM", "polymarket_aliases": ["Amsterdam"], "news_query": "Amsterdam weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "tel-aviv", "city": "Tel Aviv", "country": "IL", "region": "Middle East", "lat": 32.0853, "lon": 34.7818, "timezone": "Asia/Jerusalem", "unit": "C", "icao": "LLBG", "polymarket_aliases": ["Tel Aviv"], "news_query": "Tel Aviv weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "ankara", "city": "Ankara", "country": "TR", "region": "Middle East", "lat": 39.9334, "lon": 32.8597, "timezone": "Europe/Istanbul", "unit": "C", "icao": "LTAC", "polymarket_aliases": ["Ankara"], "news_query": "Ankara weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "beijing", "city": "Beijing", "country": "CN", "region": "Asia", "lat": 39.9042, "lon": 116.4074, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZBAA", "polymarket_aliases": ["Beijing"], "news_query": "Beijing weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "shanghai", "city": "Shanghai", "country": "CN", "region": "Asia", "lat": 31.2304, "lon": 121.4737, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZSSS", "polymarket_aliases": ["Shanghai"], "news_query": "Shanghai weather OR forecast OR typhoon", "label_dx": 8, "label_dy": -12},
    {"city_id": "shenzhen", "city": "Shenzhen", "country": "CN", "region": "Asia", "lat": 22.5431, "lon": 114.0579, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZGSZ", "polymarket_aliases": ["Shenzhen"], "news_query": "Shenzhen weather OR forecast OR typhoon", "label_dx": 8, "label_dy": -12},
    {"city_id": "singapore", "city": "Singapore", "country": "SG", "region": "Asia", "lat": 1.3521, "lon": 103.8198, "timezone": "Asia/Singapore", "unit": "C", "icao": "WSSS", "polymarket_aliases": ["Singapore"], "news_query": "Singapore weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "tokyo", "city": "Tokyo", "country": "JP", "region": "Asia", "lat": 35.6762, "lon": 139.6503, "timezone": "Asia/Tokyo", "unit": "C", "icao": "RJTT", "polymarket_aliases": ["Tokyo"], "news_query": "Tokyo weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "seoul", "city": "Seoul", "country": "KR", "region": "Asia", "lat": 37.5665, "lon": 126.9780, "timezone": "Asia/Seoul", "unit": "C", "icao": "RKSI", "polymarket_aliases": ["Seoul"], "news_query": "Seoul weather OR forecast OR heatwave", "label_dx": 8, "label_dy": -12},
    {"city_id": "chengdu", "city": "Chengdu", "country": "CN", "region": "Asia", "lat": 30.5728, "lon": 104.0668, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZUUU", "polymarket_aliases": ["Chengdu"], "news_query": "Chengdu weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "chongqing", "city": "Chongqing", "country": "CN", "region": "Asia", "lat": 29.5630, "lon": 106.5516, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZUCK", "polymarket_aliases": ["Chongqing"], "news_query": "Chongqing weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "wuhan", "city": "Wuhan", "country": "CN", "region": "Asia", "lat": 30.5928, "lon": 114.3055, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZHHH", "polymarket_aliases": ["Wuhan"], "news_query": "Wuhan weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "buenos-aires", "city": "Buenos Aires", "country": "AR", "region": "South America", "lat": -34.6037, "lon": -58.3816, "timezone": "America/Argentina/Buenos_Aires", "unit": "C", "icao": "SABE", "polymarket_aliases": ["Buenos Aires"], "news_query": "Buenos Aires weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "sao-paulo", "city": "Sao Paulo", "country": "BR", "region": "South America", "lat": -23.5558, "lon": -46.6396, "timezone": "America/Sao_Paulo", "unit": "C", "icao": "SBSP", "polymarket_aliases": ["Sao Paulo", "São Paulo"], "news_query": "Sao Paulo weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "wellington", "city": "Wellington", "country": "NZ", "region": "Oceania", "lat": -41.2865, "lon": 174.7762, "timezone": "Pacific/Auckland", "unit": "C", "icao": "NZWN", "polymarket_aliases": ["Wellington"], "news_query": "Wellington weather OR forecast OR wind", "label_dx": 8, "label_dy": -12},
]


EXTRA_WEATHER_CITIES: List[Dict[str, Any]] = [
    {"city_id": "hong-kong", "city": "Hong Kong", "country": "HK", "region": "Asia", "lat": 22.3193, "lon": 114.1694, "timezone": "Asia/Hong_Kong", "unit": "C", "icao": "VHHH", "polymarket_aliases": ["Hong Kong", "HK"], "news_query": "Hong Kong weather OR forecast OR rain OR typhoon", "label_dx": 8, "label_dy": -12},
    {"city_id": "san-francisco", "city": "San Francisco", "country": "US", "region": "North America", "lat": 37.7749, "lon": -122.4194, "timezone": "America/Los_Angeles", "unit": "F", "icao": "KSFO", "polymarket_aliases": ["San Francisco", "SF"], "news_query": "San Francisco weather OR forecast OR wind", "label_dx": 8, "label_dy": -12},
    {"city_id": "istanbul", "city": "Istanbul", "country": "TR", "region": "Middle East", "lat": 41.0082, "lon": 28.9784, "timezone": "Europe/Istanbul", "unit": "C", "icao": "LTFM", "polymarket_aliases": ["Istanbul"], "news_query": "Istanbul weather OR forecast OR storm", "label_dx": 8, "label_dy": -12},
    {"city_id": "manila", "city": "Manila", "country": "PH", "region": "Asia", "lat": 14.5995, "lon": 120.9842, "timezone": "Asia/Manila", "unit": "C", "icao": "RPLL", "polymarket_aliases": ["Manila"], "news_query": "Manila weather OR forecast OR rain OR typhoon", "label_dx": 8, "label_dy": -12},
    {"city_id": "jakarta", "city": "Jakarta", "country": "ID", "region": "Asia", "lat": -6.2088, "lon": 106.8456, "timezone": "Asia/Jakarta", "unit": "C", "icao": "WIII", "polymarket_aliases": ["Jakarta"], "news_query": "Jakarta weather OR forecast OR rain OR flood", "label_dx": 8, "label_dy": -12},
    {"city_id": "taipei", "city": "Taipei", "country": "TW", "region": "Asia", "lat": 25.0330, "lon": 121.5654, "timezone": "Asia/Taipei", "unit": "C", "icao": "RCTP", "polymarket_aliases": ["Taipei"], "news_query": "Taipei weather OR forecast OR rain OR typhoon", "label_dx": 8, "label_dy": -12},
    {"city_id": "busan", "city": "Busan", "country": "KR", "region": "Asia", "lat": 35.1796, "lon": 129.0756, "timezone": "Asia/Seoul", "unit": "C", "icao": "RKPK", "polymarket_aliases": ["Busan"], "news_query": "Busan weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "cape-town", "city": "Cape Town", "country": "ZA", "region": "Africa", "lat": -33.9249, "lon": 18.4241, "timezone": "Africa/Johannesburg", "unit": "C", "icao": "FACT", "polymarket_aliases": ["Cape Town"], "news_query": "Cape Town weather OR forecast OR wind", "label_dx": 8, "label_dy": -12},
    {"city_id": "karachi", "city": "Karachi", "country": "PK", "region": "Asia", "lat": 24.8607, "lon": 67.0011, "timezone": "Asia/Karachi", "unit": "C", "icao": "OPKC", "polymarket_aliases": ["Karachi"], "news_query": "Karachi weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "kuala-lumpur", "city": "Kuala Lumpur", "country": "MY", "region": "Asia", "lat": 3.1390, "lon": 101.6869, "timezone": "Asia/Kuala_Lumpur", "unit": "C", "icao": "WMKK", "polymarket_aliases": ["Kuala Lumpur"], "news_query": "Kuala Lumpur weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "guangzhou", "city": "Guangzhou", "country": "CN", "region": "Asia", "lat": 23.1291, "lon": 113.2644, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZGGG", "polymarket_aliases": ["Guangzhou"], "news_query": "Guangzhou weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "helsinki", "city": "Helsinki", "country": "FI", "region": "Europe", "lat": 60.1699, "lon": 24.9384, "timezone": "Europe/Helsinki", "unit": "C", "icao": "EFHK", "polymarket_aliases": ["Helsinki"], "news_query": "Helsinki weather OR forecast OR cold", "label_dx": 8, "label_dy": -12},
    {"city_id": "jeddah", "city": "Jeddah", "country": "SA", "region": "Middle East", "lat": 21.4858, "lon": 39.1925, "timezone": "Asia/Riyadh", "unit": "C", "icao": "OEJN", "polymarket_aliases": ["Jeddah"], "news_query": "Jeddah weather OR forecast OR heat", "label_dx": 8, "label_dy": -12},
    {"city_id": "lucknow", "city": "Lucknow", "country": "IN", "region": "Asia", "lat": 26.8467, "lon": 80.9462, "timezone": "Asia/Kolkata", "unit": "C", "icao": "VILK", "polymarket_aliases": ["Lucknow"], "news_query": "Lucknow weather OR forecast OR heat OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "moscow", "city": "Moscow", "country": "RU", "region": "Europe", "lat": 55.7558, "lon": 37.6173, "timezone": "Europe/Moscow", "unit": "C", "icao": "UUEE", "polymarket_aliases": ["Moscow"], "news_query": "Moscow weather OR forecast OR cold", "label_dx": 8, "label_dy": -12},
    {"city_id": "panama-city", "city": "Panama City", "country": "PA", "region": "North America", "lat": 8.9824, "lon": -79.5199, "timezone": "America/Panama", "unit": "C", "icao": "MPTO", "polymarket_aliases": ["Panama City"], "news_query": "Panama City weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
    {"city_id": "qingdao", "city": "Qingdao", "country": "CN", "region": "Asia", "lat": 36.0671, "lon": 120.3826, "timezone": "Asia/Shanghai", "unit": "C", "icao": "ZSQD", "polymarket_aliases": ["Qingdao"], "news_query": "Qingdao weather OR forecast OR rain", "label_dx": 8, "label_dy": -12},
]


def load_weather_cities(limit: int | None = None) -> List[Dict[str, Any]]:
    rows = [dict(city) for city in [*WEATHER_CITIES, *EXTRA_WEATHER_CITIES]]
    if limit is None:
        return rows
    return rows[: max(1, min(int(limit), len(rows)))]
